/*------------CSS STYLESHEET DYNAMICALLY GENERATED BY SPARKY---------------*/

<?php if($googleWebFonts){ ?>
/*------------GOOGLE FONTS---------------*/
<?php echo $googleWebFonts; } ?>

html {
    font-size:<?php echo $pSize; ?>px;
}

body {
    color:<?php echo $pColor; ?>;
    font-family:<?php echo $pFamily; ?>;
<?php if($textDirection!="rtl") { ?>     text-align:<?php echo $pAlign; ?>;<?php } ?>
    font-weight:<?php echo $pWeight; ?>;
    font-style:<?php echo $pStyle; ?>;
<?php if($textDirection=="rtl") { ?>    direction:rtl;
<?php } ?>
<?php if(!$bodyBgImageSwitch) { ?>
    background:<?php echo $bodyBgColor; ?>;
<?php } if($bodyBgImageSwitch && $bodyBgImageFile) { ?>
    background:<?php echo $bodyBgColor; ?> url(<?php echo $this->baseurl."/".$bodyBgImageFile; ?>) <?php echo $bodyBgImageVerticalAlign.' '.$bodyBgImageHorizontalAlign.' '.$bodyBgImageRepeat; if($bodyBgImageFixedSwitch) { echo " fixed"; } ?>;
<?php } ?>
}

div.container {
    background:<?php echo $containerBgColor; ?>;
}

.span1 {
    width: 8.33333333%;
}
.span2 {
    width: 16.66666667%;
}
.span3 {
    width: 25%;
}
.span4 {
    width: 33.33333333%;
}
.span5 {
    width: 41.66666667%;
}
.span6 {
    width: 50%;
}
.span7 {
    width: 58.33333333%;
}
.span8 {
    width: 66.66666667%;
}
.span9 {
    width: 75%;
}
.span10 {
    width: 83.33333333%;
}
.span11 {
    width: 91.66666667%;
}
.span12 {
    width: 100%;
}

.full .container, .full .row {
    width:100%;
}

.full .cell_pad {
    margin: 0;
    padding: 0;
}

<?php if($enableResponsive && $templateWidth > 767){ ?>

/*------------ SCREEN < 768px AND < TEMPLATE WIDTH ---------------*/

@media (max-width: 767px) {
    .container {
        width: 100%;
    }

    [class*="span"] {
        width: 100%;
    }

    .two [class*="span"] {
        width: 50%;
    }

    .full .container, .full .row {
        width:100%;
    }

    .full .cell_pad {
        margin: 0;
        padding: 0;
    }
}

<?php } ?>

<?php if($enableResponsive && $templateWidth > 768){ ?>
/*------------ SCREEN >= 768px AND < TEMPLATE WIDTH ---------------*/

@media (min-width: 768px) {

    .container {
        width: 750px;
    }

}
<?php } ?>

<?php if($enableResponsive && $templateWidth > 992){ ?>
/*------------ SCREEN >= 992px AND < TEMPLATE WIDTH ---------------*/

@media (min-width: 992px) {
    .container {
        width: 970px;
    }
}
<?php } ?>

<?php if($enableResponsive && $templateWidth > 1200){ ?>
/*------------ SCREEN >= 1200px AND < TEMPLATE WIDTH ---------------*/

@media (min-width: 1200px) {
    .container {
        width: 1170px;
    }
}
<?php } ?>

/*------------ SCREEN >= TEMPLATE WIDTH ---------------*/

<?php if($enableResponsive){
    $templateWidthPlus = $templateWidth + 30; ?>
@media (min-width: <?php echo $templateWidthPlus; ?>px) {<?php } ?>

.container, .row {
<?php if(!$fluidWidth) { ?>
    width:<?php echo $templateWidth; ?>px;
<?php }else{ ?>
    width:100%;
<?php } ?>
}

[class*="span"] {
    margin-left: 0;
}

<?php
$cell_size = 8.33333333;
$empty_no = 0;

foreach($module_grid as $gridRow){
//$gridRow[0] - Name
//$gridRow[1] - Class
//$gridRow[2] - ModulePos1,ModulePos2...
//$gridRow[3] - Holds content flag: true/false
    foreach($gridRow[2] as $mposition){
    //$mposition[0] - position name 
    //$mposition[1] - number of grid cells occupied by position
    //$mposition[2] - number of empty cells left of module
    
    $mpwidth = $cell_size * $mposition[1];  
    $mpleft_off = $cell_size * $mposition[2];  
    if( $mposition[0] == "joom_content"){
        if($mpleft_off){
?>
.mp_empty<?php echo $empty_no; ?>{
    width:<?php echo $mpleft_off; ?>%;
}

<?php
            $empty_no++;
        }  
?>
.content_sparky {
    width:<?php echo $mpwidth; ?>%;
}

<?php
        }else{
            if($mpleft_off){
?>
.mp_empty<?php echo $empty_no; ?>{
    width:<?php echo $mpleft_off; ?>%;
}

<?php
                $empty_no++;
            }
        }
    }
}
if($enableResponsive){
?>
}
<?php } ?>

.one .span1 {
    width: 8.33333333%;
}
.one .span2 {
    width: 16.66666667%;
}
.one .span3 {
    width: 25%;
}
.one .span4 {
    width: 33.33333333%;
}
.one .span5 {
    width: 41.66666667%;
}
.one .span6 {
    width: 50%;
}
.one .span7 {
    width: 58.33333333%;
}
.one .span8 {
    width: 66.66666667%;
}
.one .span9 {
    width: 75%;
}
.one .span10 {
    width: 83.33333333%;
}
.one .span11 {
    width: 91.66666667%;
}
.one .span12 {
    width: 100%;
}

.fluid .container, .fluid .container .row {
    width: 100%;
}

.cell_pad {
    padding:<?php echo $cellPaddingVertical; ?>px <?php echo $cellPaddingHorizontal; ?>px;
    margin:<?php echo $cellMarginVertical; ?>px <?php echo $cellMarginHorizontal; ?>px;
}

/*------------ COMMON SETTINGS ---------------*/

a {
    color:<?php echo $linksColor; ?>;
    font-weight:<?php echo $linksWeight; ?>;
    font-style:<?php echo $linksStyle; ?>;
    text-decoration:<?php if($linksUnderline) { echo "underline"; }else{ echo "none"; } ?>;
}

a:hover {
    color:<?php echo $linksHoverColor; ?>;
    text-decoration:<?php if($linksUnderlineHover) { echo "underline"; }else{ echo "none"; } ?>;
}

h1, h1 a {
    color:<?php echo $h1Color; ?>;
    font-size:<?php echo $h1Size; ?>px;
    font-family:<?php echo $h1Family; ?>;
 <?php if($textDirection!="rtl") { ?>   text-align:<?php echo $h1Align; ?>;<?php } ?>
    font-weight:<?php echo $h1Weight; ?>;
    font-style:<?php echo $h1Style; ?>;
    <?php if($h1Underline) { ?>text-decoration:underline;<?php } ?>
}

h2, h2 a {
    color:<?php echo $h2Color; ?>;
    font-size:<?php echo $h2Size; ?>px;
    font-family:<?php echo $h2Family; ?>;
<?php if($textDirection!="rtl") { ?>    text-align:<?php echo $h2Align; ?>;<?php } ?>
    font-weight:<?php echo $h2Weight; ?>;
    font-style:<?php echo $h2Style; ?>;
    <?php if($h2Underline) { ?>text-decoration:underline;<?php } ?>
}

h3 {
    color:<?php echo $h3Color; ?>;
    font-size:<?php echo $h3Size; ?>px;
    font-family:<?php echo $h3Family; ?>;
<?php if($textDirection!="rtl") { ?>    text-align:<?php echo $h3Align; ?>;<?php } ?>
    font-weight:<?php echo $h3Weight; ?>;
    font-style:<?php echo $h3Style; ?>;
    <?php if($h3Underline) { ?>text-decoration:underline;<?php } ?>
}

h4 {
    color:<?php echo $h4Color; ?>;
    font-size:<?php echo $h4Size; ?>px;
    font-family:<?php echo $h4Family; ?>;
<?php if($textDirection!="rtl") { ?>    text-align:<?php echo $h4Align; ?>;<?php } ?>
    font-weight:<?php echo $h4Weight; ?>;
    font-style:<?php echo $h4Style; ?>;
    <?php if($h4Underline) { ?>text-decoration:underline;<?php } ?>
}

img {
    border:none;
}

/*--------------LOGO----------------*/

.sparky_logo, .sparky_logo a {
	color:<?php echo $logoColor; ?>;
    font-size:<?php echo $logoSize; ?>px;
    font-family:<?php echo $logoFamily; ?>;
    font-weight:<?php echo $logoWeight; ?>;
    font-style:<?php echo $logoStyle; ?>;
<?php if($textDirection!="rtl") { ?>	text-align:<?php echo $logoAlign; ?>;<?php } ?>
    text-decoration:none;
}

.sparky_slogan {
	color:<?php echo $sloganColor; ?>;
    font-size:<?php echo $sloganSize; ?>px;
    font-family:<?php echo $sloganFamily; ?>;
    font-weight:<?php echo $sloganWeight; ?>;
    font-style:<?php echo $sloganStyle; ?>;
<?php if($textDirection!="rtl") { ?>	text-align:<?php echo $sloganAlign; ?>;<?php } ?>
}

<?php
foreach($mnucfg as $menu_name => $menu) {
if(isset($menu['font_family_hotfont'])){
	$obj = json_decode(str_replace("\\","",$menu['font_family_hotfont']), true);
	$menu['font_family'] = $obj['fontFamily'];
	$menu['font_weight'] = $obj['fontWeight'];
	$menu['font_style'] = $obj['fontStyle'];
}
if(isset($menu['font_family_sub_hotfont'])){
	$obj2 = json_decode(str_replace("\\","",$menu['font_family_sub_hotfont']), true);
	$menu['font_family_sub'] = $obj2['fontFamily'];
	$menu['font_weight_sub'] = $obj2['fontWeight'];
	$menu['font_style_sub'] = $obj2['fontStyle'];
}	
if($menu['type'] == "standard") { 
?>

/*--------------STANDARD----------------*/

ul.mnu_<?php echo $menu_name;?> {
    margin:0;
    padding:0;
<?php if($textDirection!="rtl") { ?>    text-align:<?php echo $menu['text_align']; ?>;<?php } ?>
}

ul.mnu_<?php echo $menu_name;?> ul {
    margin:<?php echo $menu['margin_sub']; ?>px;
    padding:0;
}

.mnu_<?php echo $menu_name;?> li {
    display:block;
}

<?php if($menu['direction'] == "horizontal") { ?>
.mnu_<?php echo $menu_name;?> > li {
    display:inline-block;
}
<?php } ?>

.mnu_<?php echo $menu_name;?> > li {
    margin-bottom:<?php echo $menu['bottom_margin']; ?>px;
    padding:<?php echo $menu['vertical_padding']; ?>px <?php echo $menu['horizontal_padding']; ?>px;
    font-size:<?php echo $menu['font_size']; ?>px;
    font-weight:<?php echo $menu['font_weight']; ?>;
    font-style:<?php echo $menu['font_style']; ?>;
<?php if($textDirection!="rtl") { ?>    text-align:<?php echo $menu['text_align']; ?>;<?php } ?>
}

.mnu_<?php echo $menu_name;?> > li > a {
    color:<?php echo $menu['text_color']; ?>;
    font-family:<?php echo $menu['font_family']; ?>;
    font-weight:<?php echo $menu['font_weight']; ?>;
    font-style:<?php echo $menu['font_style']; ?>;
}

.mnu_<?php echo $menu_name;?> > li > a:hover {
    color:<?php echo $menu['links_hover_color']; ?>;
}

.mnu_<?php echo $menu_name;?> > li li {
    margin:0;
    padding:0;
    font-size:<?php echo $menu['font_size_sub']; ?>px;
    line-height:<?php echo $menu['subitem_height']; ?>px;
    font-weight:<?php echo $menu['font_weight']; ?>;
    font-style:<?php echo $menu['font_style']; ?>;
 <?php if($textDirection!="rtl") { ?>   text-align:<?php echo $menu['text_align']; ?>;<?php } ?>
}

.mnu_<?php echo $menu_name;?> > li li a {
    color:<?php echo $menu['text_color_sub']; ?>;
    font-family:<?php echo $menu['font_family_sub']; ?>;
    font-weight:<?php echo $menu['font_weight']; ?>;
    font-style:<?php echo $menu['font_style']; ?>;
<?php if($textDirection!="rtl") { ?>    text-align:<?php echo $menu['text_align']; ?>;<?php } ?>
}

.mnu_<?php echo $menu_name;?> > li li a:hover {
    color:<?php echo $menu['links_hover_color_sub']; ?>;   
}

<?php } elseif($menu['type'] == "acc") { ?>

/*--------------ACCORDION----------------*/

.mnu_<?php echo $menu_name;?> ul {
    background:<?php echo $menu['accordion_pane_bg']; ?>;
}
.mnu_<?php echo $menu_name;?> li, .mnu_<?php echo $menu_name;?> li li ul  {
    border:<?php echo $menu['accordion_pane_border_size']; ?>px solid <?php echo $menu['accordion_pane_border_color']; ?>;
    border-radius:<?php echo $menu['accordion_pane_border_radius']; ?>px;
    background:<?php echo $menu['accordion_pane_bg']; ?>;
}

.mnu_<?php echo $menu_name;?> li a {
    font-family:<?php echo $menu['font_family']; ?>;
    font-size:<?php echo $menu['font_size']; ?>px;
    color:<?php echo $menu['text_color']; ?>;
}

.mnu_<?php echo $menu_name;?> li a:hover {
	color:<?php echo $menu['links_hover_color']; ?> !important;
}

.mnu_<?php echo $menu_name;?> li ul li a {
    color:<?php echo $menu['text_color_sub']; ?>;
    font-size:<?php echo $menu['font_size_sub']; ?>px;
}

.mnu_<?php echo $menu_name;?> li ul li a:hover {
    color:<?php echo $menu['links_hover_color_sub']; ?> !important;
}
<?php } elseif($menu['type'] == "navv") { ?>

/*--------------DROP-DOWN----------------*/

ul.mnu_<?php echo $menu_name;?> {
    margin:0;
    padding:0;
    list-style-type:none;
    list-style-position:outside;
    position:absolute;
    z-index:100;
    white-space:nowrap;
    text-align:<?php echo $menu['drop_down_alignment']; ?>;
    position:relative;
    font-family:<?php echo $menu['font_family']; ?>;
}

.mnu_<?php echo $menu_name;?> ul {
    margin:0;
    padding:0;
    list-style-type:none;
    list-style-position:outside;
    position:absolute;
    z-index:100;
    background:<?php echo $menu['drop_down_pane_bg']; ?>;
}

.mnu_<?php echo $menu_name;?> ul {
    width:<?php echo $menu['drop_down_pane_width']; ?>px;
    border:<?php echo $menu['border_size_sub_lvl']; ?>px solid <?php echo $menu['border_color_sub_lvl']; ?>;
    padding:<?php echo $menu['drop_down_pane_padding']; ?>px;
}

.mnu_<?php echo $menu_name;?> > li > a, .mnu_<?php echo $menu_name;?> > li > span {
    display:block;
    margin:0;
    text-decoration:none;
    color:<?php echo $menu['text_color']; ?>;
    font-size:<?php echo $menu['font_size']; ?>px;
    padding-left:<?php echo $menu['drop_down_button_horiz_padding']; ?>px;
    padding-right:<?php echo $menu['drop_down_button_horiz_padding']; ?>px;
    padding-top:<?php echo $menu['drop_down_button_top_padding']; ?>px;
    padding-bottom:0;
    font-weight:<?php echo $menu['font_weight']; ?>;
    font-style:<?php echo $menu['font_style']; ?>;
    height:<?php echo $menu['drop_down_button_height']; ?>px;
    cursor:pointer;
}

.mnu_<?php echo $menu_name;?> > li.active > a, .mnu_<?php echo $menu_name;?> > li.active > span {
    color:<?php echo $menu['active_text_color']; ?> !important;
    cursor:pointer;
}

.mnu_<?php echo $menu_name;?> > li > a:hover, .mnu_<?php echo $menu_name;?> > li:hover > a,
.mnu_<?php echo $menu_name;?> > li > a:hover, .mnu_<?php echo $menu_name;?> > li:hover > span {
    color:<?php echo $menu['links_hover_color']; ?>;
}

.mnu_<?php echo $menu_name;?> > li {
    display:inline-block;
    position:relative;
<?php if ($menu['drop_down_button_width']) { ?>    width:<?php echo $menu['drop_down_button_width']; ?>px;<?php } ?>
<?php if($textDirection!="rtl") { ?>    text-align:<?php echo $menu['text_align']; ?>;<?php } ?>
    margin:0;
    padding:0;
    border-right:<?php echo $menu['border_size_first_lvl']; ?>px solid <?php echo $menu['border_color_first_lvl']; ?>;
    border-bottom:<?php echo $menu['border_size_first_lvl']; ?>px solid <?php echo $menu['border_color_first_lvl']; ?>;
    border-top:<?php echo $menu['border_size_first_lvl']; ?>px solid <?php echo $menu['border_color_first_lvl']; ?>;
    background:<?php echo $menu['button_bg']; ?>;
}

.mnu_<?php echo $menu_name;?> > li.active {
    background:<?php echo $menu['active_button_bg']; ?>;
}

.mnu_<?php echo $menu_name;?> > li:first-child {
    border-left:<?php echo $menu['border_size_first_lvl']; ?>px solid <?php echo $menu['border_color_first_lvl']; ?>;
}

.mnu_<?php echo $menu_name;?> li:hover {
    position:relative;
    background:<?php echo $menu['button_hover_bg']; ?>;
}

.mnu_<?php echo $menu_name;?> li ul li:hover {
    background:<?php echo $menu['drop_down_hover_bg']; ?>;
}

.mnu_<?php echo $menu_name;?> li ul li {
    height:<?php echo $menu['drop_down_pane_height']; ?>px;
    border-bottom:<?php echo $menu['border_size_sub_lvl']; ?>px solid <?php echo $menu['border_color_sub_lvl']; ?>;
    padding:0 <?php echo $menu['drop_down_pane_horiz_padding']; ?>px;
<?php if($textDirection!="rtl") { ?>    text-align:left;<?php } ?>
}

.mnu_<?php echo $menu_name;?> li ul a, .mnu_<?php echo $menu_name;?> li ul span {
    line-height:<?php echo $menu['drop_down_pane_height']; ?>px;
    font-size:<?php echo $menu['font_size_sub']; ?>px;
    color:<?php echo $menu['text_color_sub']; ?>;
    font-weight:<?php echo $menu['font_weight_sub']; ?>;
	font-family:<?php echo $menu['font_family_sub']; ?>;
    font-style:<?php echo $menu['font_style_sub']; ?>;
    padding-top:0;
    cursor:pointer;
}

.mnu_<?php echo $menu_name;?> li ul li:hover > a,
.mnu_<?php echo $menu_name;?> li ul li:hover > span {
    color:<?php echo $menu['links_hover_color_sub']; ?>;
}

.mnu_<?php echo $menu_name;?> li ul ul {
<?php if($textDirection=="rtl") { ?>
    right:<?php echo $menu['drop_down_pane_width']; ?>px;
<?php }else{ ?>
    left:<?php echo $menu['drop_down_pane_width']; ?>px;
<?php } ?>
    margin-top:-<?php echo $menu['drop_down_pane_padding']; ?>px;
}

.mnu_<?php echo $menu_name;?> ul ul {
    top:0px;
}

<?php if($menu['arrows']) { ?>
.mnu_<?php echo $menu_name;?> > li.parent {
    background-image:url(<?php echo $template_path; ?>/images/arrow_down.png);
    background-repeat:no-repeat;
    background-position:right center;
    padding-right:15px;
}

.mnu_<?php echo $menu_name;?> li li.parent {
    background:url(<?php echo $template_path; ?>/images/arrow_right.png) no-repeat right center;
}
<?php } ?>

.mnu_<?php echo $menu_name;?> .sub {
    font-size:10px;
    line-height:normal;
    display:block;
}

.mnu_<?php echo $menu_name;?> > li > ul {
    display: none;
}

<?php } elseif($menu['type'] == "navh") { ?>

/*--------------HORIZONTAL----------------*/

.mnu_<?php echo $menu_name;?> {
    background:<?php echo $menu['tab_color']; ?>;
    width:100%;
    height:<?php echo $menu['tab_height']; ?>px;
    font-family:<?php echo $menu['font_family']; ?>;
}

.mnu_<?php echo $menu_name;?> > li {
    background:<?php echo $menu['button_bg']; ?>;
    line-height:<?php echo $menu['tab_height']; ?>px;
    padding:0 <?php echo $menu['horiz_button_padding']; ?>px;
    margin:0;
    border:<?php echo $menu['border_size_first_lvl']; ?>px solid <?php echo $menu['border_color_first_lvl']; ?>;
<?php if (!$menu['margin_size']) { ?>border-left:none;<?php } ?>
    border-bottom:none;
    margin:0 <?php echo $menu['margin_size']; ?>px;
    -webkit-radius:<?php echo $menu['border_radius']; ?>px <?php echo $menu['border_radius']; ?>px 0 0;
    -moz-radius:<?php echo $menu['border_radius']; ?>px <?php echo $menu['border_radius']; ?>px 0 0;
    border-radius:<?php echo $menu['border_radius']; ?>px <?php echo $menu['border_radius']; ?>px 0 0;
}

.mnu_<?php echo $menu_name;?> > li:first-child {
    border-left:<?php echo $menu['border_size_first_lvl']; ?>px solid <?php echo $menu['border_color_first_lvl']; ?>;
}

.mnu_<?php echo $menu_name;?> > li:hover, .mnu_<?php echo $menu_name;?> > li.parent:hover ,.mnu_<?php echo $menu_name;?> > li.active_tab {
    background:<?php echo $menu['button_hover_bg']; ?>;
}

.mnu_<?php echo $menu_name;?> > li.active {
    background:<?php echo $menu['active_button_bg']; ?>;
    border-color:<?php echo $menu['border_color_active']; ?>;
    border-left:<?php echo $menu['border_size_first_lvl']; ?>px solid <?php echo $menu['border_color_active']; ?>;
}

.mnu_<?php echo $menu_name;?> > li.active a {
    color:<?php echo $menu['active_text_color']; ?>;
}

.mnu_<?php echo $menu_name;?> > li a:hover {
    color:#FFF;
}
 
.mnu_<?php echo $menu_name;?> > li > a {
    font-size:<?php echo $menu['font_size']; ?>px;
    color:<?php echo $menu['text_color']; ?>;
}

.mnu_<?php echo $menu_name;?> > li > a:hover {
    color:<?php echo $menu['links_hover_color']; ?>;
}

.mnu_<?php echo $menu_name;?>, .mnu_<?php echo $menu_name;?> ul {
    margin:0;
    padding:0;
    list-style-type:none;
    list-style-position:outside;
}

.mnu_<?php echo $menu_name;?> li a {
    display:block;
    text-decoration:none;
}

.mnu_<?php echo $menu_name;?> ul {
    position: absolute;
    z-index:200;
    float: left;
}

.mnu_<?php echo $menu_name;?> ul {
    display:none;
}

.mnu_<?php echo $menu_name;?> > li , .mnu_<?php echo $menu_name;?> > li  > ul > li {
    float:left;
}

.mnu_<?php echo $menu_name;?> > li:hover > ul {
    display:block;
}

.mnu_<?php echo $menu_name;?> > li.active > ul {
    display: block;
}

.navh_submenu {
    font-family:<?php echo $menu['font_family_sub']; ?>;
    float: left;
    clear: both;
}

.navh_submenu li {
    display: block;
}

div.navh_submenu {
    background:<?php echo $menu['tab_color_sub']; ?>;
    height:<?php echo $menu['tab_height_sub']; ?>px;
    line-height:<?php echo $menu['tab_height_sub']; ?>px;
    width:100%;
}

div.navh_submenu ul {
    margin: 0;
    padding: 0;
}

div.navh_submenu ul > li {
    padding:0 <?php echo $menu['horiz_button_padding_sub']; ?>px;
    margin:0;
    float:left;
}

div.navh_submenu ul > li > a {
    color:<?php echo $menu['text_color_sub']; ?> !important;
    font-size:<?php echo $menu['font_size_sub']; ?>px;
}

div.navh_submenu ul > li > a:hover {
    color:<?php echo $menu['links_hover_color_sub']; ?> !important;
}

div.navh_submenu ul > li > ul {
    padding:<?php echo $menu['horiz_pane_padding_sub_sub']; ?>px;
    background:<?php echo $menu['tab_color_sub_sub']; ?>;
    position: absolute;
    margin-left:-<?php echo $menu['horiz_button_padding_sub']; ?>px;
}

div.navh_submenu ul > li > ul > li {
    width:<?php echo $menu['tab_width_sub_sub']; ?>px;
    line-height:<?php echo $menu['horiz_pane_menu_item_height_sub_sub']; ?>px;
    padding:0;
    margin:0;
    float:none;
}

div.navh_submenu ul > li > ul > li > a {
    color:<?php echo $menu['text_color_sub_sub']; ?> !important;
    font-size:<?php echo $menu['font_size_sub_sub']; ?>px;
}

div.navh_submenu ul > li > ul > li > a:hover {
    color:<?php echo $menu['links_hover_color_sub_sub']; ?> !important;
}

div.navh_submenu ul ul ul {
<?php if($textDirection!="rtl") { ?>
    left: <?php echo $menu['tab_width_sub_sub']; ?>px;<?php }else{ ?>
    right: <?php echo $menu['tab_width_sub_sub']; ?>px;<?php } ?>

    margin-top:-40px;
}

div.navh_submenu > ul { 
    min-width: 100%;
    min-height: 30px;
    position:absolute;
    display:none;
}

div.navh_submenu > ul.active_sub {
    display:block;
    position:static;
}
<?php }
}

if($enableResponsiveMenu) {
?>
/*--------------RESPONSIVE TOP MENU----------------*/

.js .nav-collapse {
    clip: rect(0 0 0 0);
    max-height: 0;
    position: absolute;
    display: block;
    zoom: 1;
}

.nav-collapse.opened {
    max-height: 9999px;
    position:absolute;
}

.nav-collapse.opened > ul {
    position: fixed;
    top: 0;
    left: 5%;
    width: 90%;
    background:#444;
}

.nav-collapse.opened > ul ul {
    width: 100%;
    position: relative;
    left:0;
    padding:0;
    margin:0;
    background:#444;
    border:0;
}

.nav-collapse.opened > ul ul li {
    height:auto;
}

.nav-collapse.opened li {
    width: 100%;
    display: block;
    padding-left: 0;
    padding-right: 0;
}

.nav-collapse.opened li.active, .nav-collapse.opened li:hover {
    background:#333;
}

.nav-collapse.opened li.active a {
    color:#fff !important;
}

.nav-collapse.opened li a {
    padding:5px 15px;
    margin:0;
    line-height:30px;
    height:30px;
    color:#fff !important;
}

.nav-toggle {
    -webkit-tap-highlight-color: rgba(0,0,0,0);
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    -o-user-select: none;
    user-select: none;
    <?php if($menuIconImage) { ?>
    background: url(<?php echo $this->baseurl."/".$menuIconImage; ?>);
    <?php }else{ ?>
    background: url(<?php echo $template_path."/images/tinynav.png"; ?>);
    <?php } ?>
    width: 40px;
    height: 30px;
    text-indent:-9999px;
    display:inline-block;
    float:right;
}

.nav-toggle.active {
    position: absolute;
    z-index: 999;
    right: 5%;
    top: 0;
    margin-top:5px;
    margin-right:15px;
    background-position: bottom;
}

#blocker {
    position:fixed;
    width:100%;
    height:100%;
    left:0;
    top:0;
    right:0;
    bottom:0;
    z-index:9999;
}

@media screen and (min-width: <?php echo $responsiveMenuTriggerValue; ?>px) {

    .js .nav-collapse {
        position: relative;
    }

    .js .nav-collapse.closed {
        max-height: none;
    }

    .nav-toggle {
        display: none;
    }

}

@media screen and (max-width: <?php echo $responsiveMenuTriggerValue; ?>px) {

    .nav-collapse.closed {
        overflow:hidden;
    }

}
<?php }
if ($topPanelSwitch) { ?>

/*--------------TOP PANEL ----------------*/

.sparky_top_panel_button {
	width:<?php echo $topPanelButtonWidth; ?>px;
	height:<?php echo $topPanelButtonHeight; ?>px;
	line-height:<?php echo $topPanelButtonHeight; ?>px;
	background:<?php echo $topPanelButtonBgColor; ?>;
	color:<?php echo $topPanelButtonTextColor; ?>;
	font-size:<?php echo $topPanelButtonTextSize; ?>px;
    border:1px solid <?php echo $topPanelButtonBorderColor; ?>;
    border-top:none;
    -webkit-border-radius:0 0 <?php echo $topPanelButtonBorderRadius; ?>px <?php echo $topPanelButtonBorderRadius; ?>px;
    -moz-border-radius:0 0 <?php echo $topPanelButtonBorderRadius; ?>px <?php echo $topPanelButtonBorderRadius; ?>px;
	border-radius:0 0 <?php echo $topPanelButtonBorderRadius; ?>px <?php echo $topPanelButtonBorderRadius; ?>px;
}

.sparky_top_panel_container h3 {
	color:<?php echo $topPanelH3Color; ?>;
}

.sparky_top_panel_container {
	color:<?php echo $topPanelTextColor; ?>;
    position:absolute;
    width:100%;
}

.sparky_top_panel_button {
    margin:0 auto;
    text-align:center;
    cursor:pointer;
}

.close_button {
    display:none;
}
<?php } ?>

<?php if ($scrollToTopSwitch) { ?>

/*--------------SCROLL TO TOP----------------*/

#back-top {
    position: fixed;
	<?php if($scrollToTopPosition=="bottom_right") { ?>
	bottom: 25px;
	right: 25px;
    <?php }elseif($scrollToTopPosition=="bottom_left") { ?>
    bottom: 25px;
	left: 25px;
    <?php }elseif($scrollToTopPosition=="top_right") { ?>
    top: 5px;
	right: 25px;
    <?php }else{ ?>
    top: 5px;
	left: 25px;
    <?php } ?>
}

#back-top span {
    width: 60px;
    height: 60px;
    display: block;
    margin-bottom: 7px;
    background: url(<?php echo $this->baseurl."/".$scrollToTopImageFile; ?>) no-repeat center center;
    cursor: pointer;
    -webkit-transition: 1s;
    -moz-transition: 1s;
    transition: 1s;
}
<?php } ?>

/*--------------FONT RESIZE----------------*/

#font_resize a {
    padding:0 2px;
}

<?php if ($imageAnimation) { ?>
/*--------------IMAGE ANIMATION----------------*/

img.img-with-animation {
    opacity: 0;
    position: relative;
}

img.img-with-animation[data-animation="grow-in"] {
    opacity: 0;
    transform: scale(0.4);
    -webkit-transform: scale(0.4);
    -o-transform: scale(0.4);
    -moz-transform: scale(0.4);
    transition: opacity 0.6s cubic-bezier(0.15, 0.84, 0.35, 1.25);
    -webkit-transition: opacity 0.6s cubic-bezier(0.15, 0.84, 0.35, 1.25);
    -moz-transition: opacity 0.6s cubic-bezier(0.15, 0.84, 0.35, 1.25);
    -o-transition: opacity 0.6s cubic-bezier(0.15, 0.84, 0.35, 1.25);
}

img.img-with-animation[data-animation="fade-in-from-left"] {
    left: -40px;
}

img.img-with-animation[data-animation="fade-in-from-right"] {
    right: -40px;
}

img.img-with-animation[data-animation="fade-in-from-bottom"] {
    bottom: -100px;
}
<?php } ?>

/*--------------FLOATING ROW (usually for top menu)----------------*/

@-webkit-keyframes topmenushow {
    0% {
        opacity: 1;
        -webkit-transform: translateY(-50px); -moz-transform: translateY(-50px);  -moz-transform: translateY(-50px); 
    }
    
    100% {
        opacity: 1;
        -webkit-transform: translateY(0); -moz-transform: translateY(0);
    }
}

@-moz-keyframes topmenushow {
    0% {
        opacity: 1;
        -webkit-transform: translateY(-50px); -moz-transform: translateY(-50px);  -moz-transform: translateY(-50px); 
    }
    
    100% {
        opacity: 1;
        -webkit-transform: translateY(0); -moz-transform: translateY(0);
    }
}

@-o-keyframes topmenushow {
    0% {
        opacity: 1;
        -webkit-transform: translateY(-50px); -moz-transform: translateY(-50px);  -moz-transform: translateY(-50px); 
    }
    
    100% {
        opacity: 1;
        -webkit-transform: translateY(0); -moz-transform: translateY(0);
    }
}
@keyframes topmenushow {
    0% {
        opacity: 1;
        -webkit-transform: translateY(-50px); -moz-transform: translateY(-50px);  -moz-transform: translateY(-50px); 
    }
    
    100% {
        opacity: 1;
        -webkit-transform: translateY(0); -moz-transform: translateY(0);
    }
}

.fix_menu {
    position: fixed;
    top: 0;
    z-index: 89;
    width: 100%;
    background: rgba(255,255,255,.9) !important;
}

.topmenushow {
    -webkit-animation-name: topmenushow;
    -moz-animation-name: topmenushow;
    -o-animation-name: topmenushow;
    animation-name: topmenushow;
    -webkit-animation-fill-mode: both;
    -moz-animation-fill-mode: both;
    -ms-animation-fill-mode: both;
    -o-animation-fill-mode: both;
    animation-fill-mode: both;
    -webkit-animation-duration: .5s;
    -moz-animation-duration: .5s;
    -ms-animation-duration: .5s;
    -o-animation-duration: .5s;
    animation-duration: .5s;
}